// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "SwiftTestHarness",
    dependencies: [
        .package(name: "TonicProstBuild", path: "../build/SPMPackage/macosArm64/Debug")
    ],
    targets: [
        .testTarget(
            name: "SwiftTestHarnessTests",
            dependencies: [
                .product(name: "TonicProstBuildLibrary", package: "TonicProstBuild")
            ],
            linkerSettings: [
                // The SPM package generated by Kotlin's embedSwiftExportForXcode
                // task contains Swift wrapper sources and C bridge declarations,
                // but the actual symbol implementations
                // (`__root____getExceptionMessage__...`) live in
                // `libTonicProstBuild.a` produced by the
                // `linkSwiftExportBinaryDebugStaticMacosArm64` /
                // `mergeMacosDebugSwiftExportLibraries` chain. Xcode wires
                // that archive into its own link step via
                // BUILT_PRODUCTS_DIR; a standalone `swift test` invocation
                // has to point at it explicitly. The archive lands at
                // `<repo>/build/swift-test/libTonicProstBuild.a` when the
                // embed task runs with the macOS Xcode-style environment
                // variables (see .github/workflows/swift.yml).
                .unsafeFlags([
                    "-L", "../build/swift-test",
                    "-lTonicProstBuild",
                ]),
            ]
        ),
    ]
)
